### ISSUE TITLE
PHXT-1 - Refactor the code

### ISSUE THREAD

**Issue by faisfasil** [rokitapiotr/test_PHPtravels#1]
Please make the changes according to the following list:
1 - Create the ".gitignore" file. Delete the ".idea" folder from the repository. Add the cache formats and folders to the gitignore file.
2 - According to the Page Object Pattern (POP), the conftest.py file should be placed in the main directory. Move it and make the necessary changes to save the workability of tests and framework.
3 - Review files in the Page folder. Rename the folder to "lib" to save the POP. In this folder, create the "locators.py" file and reside all locators used in other files into class-containers here.
4 - To remove the "capital case", rename the "Tests" folder to "tests"

After these changes, the framework will look better and according to Page Object Pattern.

**Comment by rokitapiotr** [comment]
done!
