### ISSUE TITLE
PHXT-2 - Refactor the code

### ISSUE THREAD

**Issue by faisfasil** [rokitapiotr/test_PHPtravels#2]
Please make the following changes:
1 - Move the locators.py into lib folder. Remove the empty locators folder. It means to be according to Page Object Pattern. 
2 - Make methods in the *_page.py files not encapsulated. They could be used in our tests.
3 - Merge the similar *_page.py files and classes inside into one file for each page. Encapsulate methods which cannot be used in final tests and used only inside classes. 
4 - Make changes in tests. Make test data and use the pytest.mark.parametrize decorators to use this data in test.
5 - Replace the if-elif-else condition in the conftest.py file with match-case.

**Comment by rokitapiotr** [comment]
done
